// <auto-generated />
namespace RicardoTest2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_001));
        
        string IMigrationMetadata.Id
        {
            get { return "201209270425296_001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
